name: Tests
on: [push, pull_request]
env:
  CI: true
  RUBY: 2.6.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "10"

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY }}

      - name: Disable gem docs
        run: 'echo "gem: --no-document" > ~/.gemrc'

      - name: Set up Ruby cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-v${{ env.RUBY }}-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.os }}-ruby-v${{ env.RUBY }}-${{ hashFiles('Gemfile') }}-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Set up npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ matrix.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Set up Bundler
        run: gem install bundler -v "~> 1.17"

      - name: Update rubygems
        run: gem update --system

      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: node --version
      - run: npm --version
      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Install bundler dependencies
        run: bundle install --deployment --jobs=4 --retry=3 --clean
#        env:
#          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Build the site
        run: bundle exec jekyll build

      - name: Run htmlproofer
        run: bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --check-external-hash --check-favicon --check-img-http --check-opengraph --disable-external --enforce-https --empty-alt-ignore --internal-domains sustainoss.org

      - name: Run tests
        run: npm test
